### ISSUE TITLE
Does it actually checks that correct type were returned by path? Does it validates path?

### ISSUE THREAD

**Issue by deser** [planttheidea/selectorator#16]
Let's say I have such selector: 
```ts
export const listOfFvPages = createSelector<AppState, PagesState>(
    ['data.fvPages'],
    fvPages => fvPages
)
```
If I change path to non-existing one, nothing warns me:
```ts
export const listOfFvPages = createSelector<AppState, PagesState>(
    ['notdata.fvPages'],
    fvPages => fvPages
)
```

This seems not very type safe.

**Comment by planttheidea** [comment]
I'm not certain what you are looking for is possible, as it would need to parse the string value and build a type interface from that resultant value. If you have any recommendations about how to improve the typings, though, PRs are always welcome! I am by no means a TypeScript guru, in fact the current typings were provided by @Dudeonyx as a benefit to the `redux-starter-kit` package (a radical improvement over the original ones I had).

**Comment by deser** [comment]
Me guru in typescript either :) @Dudeonyx, any thoughts?

**Comment by Dudeonyx** [comment]
@deser @planttheidea 
I wouldn't call myself a typescript guru either ;)

Unfortunately, nothing can be done about type checking the path because Typescript currently doesn't support concatenating string literals or RegEx type checking.

see https://github.com/Microsoft/TypeScript/issues/12754

The only way I can think of to get typechecking there would be to change the way `string` paths are entered to something like

```ts
export const listOfFvPages = createSelector<AppState, PagesState>(
    [ ['data','fvPages'] ],  // instead of ['data.fvPages']
    fvPages => fvPages
)
```

Then we would be able to typecheck  if `AppState['data']['fvPages']` exists.

So given a path `[['data','fvPages','page','chapter']]` we could typecheck for `AppState['data']['fvPages']['page']['chapter']`

This would require breaking changes and a weekend of hair pulling for whomever has to create the typings

**Comment by planttheidea** [comment]
Well, if it helps that format is supported (under the hood it's just using `get` from the `unchanged` package), so it wouldn't be a bakiyng change.

Not volunteering to have said hair-pulling session, but if anyone is willing it's ready for you. 😆

**Comment by planttheidea** [comment]
Closed due to inactivity.
